version: '3.8'

services:
  # Наш сервис с моделью
  ml_model:
    build: .
    container_name: spam_classifier_service
    ports:
      - "8000:8000"
    environment:
      # Передаем настройки через переменные окружения
      - HDFS_URL=http://namenode:9870
      - HDFS_USER=hadoop
    depends_on:
      - namenode
    networks:
      - hadoop_network

  # NameNode - "мозг" HDFS
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
    networks:
      - hadoop_network

  # DataNode - место, где реально лежат файлы
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge